# Generated by Django 4.0.3 on 2022-04-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='password',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=None)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city')),
            ],
        ),
    ]
