# Generated by Django 4.0.3 on 2022-04-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_discription_city_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(default=None, upload_to='images/locations/'),
            preserve_default=False,
        ),
    ]
